version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - ./facturacion:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
